FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

# Ferramentas básicas (opcional, mas útil)
RUN apt-get update && apt-get install -y --no-install-recommends \ libgomp1
    build-essential curl \
&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip \
&& pip install -r requirements.txt

COPY . .

ENV FLASK_APP=app.py
EXPOSE 5000
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]
